language: node_js
node_js:
  - "12"
addons:
  chrome: stable

before_install:
  - npm install -g yarn

install:
  - yarn
  - yarn bootstrap

script:
  - yarn lint
  - yarn test
  - yarn build

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: packages/angularjs/demo/dist
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: "npx lerna publish from-package --yes"
    on:
      tags: true
