language: node_js
node_js:
  - "12"
addons:
  chrome: stable

before_install:
  - npm install -g yarn

install:
  - yarn
  - yarn bootstrap

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: packages/angularjs/demo/dist
  on:
    only:
      - master
